export const FETCH_JOBS = "FETCH_JOBS";
export const JOBS_FAILED = "JOBS_FAILED";
export const JOBS_LOADING = "JOBS_LOADING";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const STUDENTS_FAILED = "STUDENTS_FAILED";
export const STUDENTS_LOADING = "STUDENTS_LOADING";

export const NOTIFY_FAILED="NOTIFY_FAILED";
export const NOTIFY_LOADING="NOTIFY_LOADING";
export const FETCH_NOTIFY="FETCH_NOTIFY";